let avlTree = AVLTree<Int>()

avlTree.insert(5)
avlTree.insert(3)
avlTree.insert(7)
avlTree.printInOrder()
print("Root: \(avlTree.root?.item)")
print("Height: \(avlTree.height)")
avlTree.insert(2)
print("Root: \(avlTree.root?.item)")
print("Height: \(avlTree.height)")
avlTree.insert(1)
print("Root: \(avlTree.root?.item)")
print("Height: \(avlTree.height)")
print("In a Binary Search Tree, the height would be 4 =)")
avlTree.printInOrder()
